//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.23 at 02:43:14 PM EDT 
//
package com.agileapps.pt.pojos;

import java.util.ArrayList;
import java.util.List;

import org.simpleframework.xml.Element;
import org.simpleframework.xml.ElementList;


public class FormTemplatePart {

	@Element
    private int id;
	@Element
    private String title;
	@ElementList
    private List<QuestionAnswer>questionAnswerList;
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public List<QuestionAnswer> getQuestionAnswerList() {
		return questionAnswerList;
	}
	public void setQuestionAnswerList(List<QuestionAnswer> questionAnswerList) {
		this.questionAnswerList = questionAnswerList;
	}
	
	
	@Override
	public String toString() {
		return "FormTemplatePart [id=" + id + ", title=" + title
				+ ", questionAnswerList=" + questionAnswerList + "]";
	}

    public void clear()
    {
    	for (QuestionAnswer questionAnswer:questionAnswerList){
    		questionAnswer.clear();
    	}
    }
    

}
