//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.23 at 02:43:14 PM EDT 
//


package com.agileapps.pt.pojos;

import java.io.Serializable;

public enum InputType  {

    TEXT,
    EMAIL,
    INTEGER,
    FLOAT,
    PHONE,
    RADIO,
    CHECKBOX;

    public String value() {
        return name();
    }

    public static InputType fromValue(String v) {
        return valueOf(v);
    }

}
